export class LoremIpsum {
    static text = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin odio non nunc viverra, id dictum lacus porttitor. Cras faucibus aliquam nisl nec elementum. Sed finibus ligula laoreet mi semper sodales. Donec rutrum iaculis porta. Phasellus sit amet lacus felis. Phasellus risus nisl, feugiat nec ipsum at, malesuada aliquet neque. Proin fermentum, sapien in finibus lacinia, mi mi volutpat ligula, eu fermentum elit est quis nunc. Vivamus eget nisl in lectus ornare dictum. Sed sodales ligula id velit tempor eleifend.

Aenean sed tortor at lorem vulputate ultrices. Nullam quis laoreet sapien. Aliquam egestas, massa vel venenatis ultrices, tellus nisl aliquam lorem, quis elementum diam orci sit amet leo. Donec vitae maximus augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer dui ligula, aliquam non sodales ac, posuere nec enim. Donec hendrerit nunc eget elit lobortis bibendum. In aliquet euismod interdum. Nunc non enim diam. Aenean id elit tellus. Phasellus turpis mauris, tristique quis nisl quis, pulvinar porta ante. Nunc porta mollis ullamcorper. In tristique iaculis arcu eget fermentum. Quisque ut arcu at arcu auctor ultrices ac quis nibh. Cras ut turpis eu felis faucibus tempor et sit amet lacus. Suspendisse a velit bibendum, consectetur mi et, tempor nunc.

Aenean et lobortis sem. Nullam luctus sodales turpis. Ut nunc enim, mattis non congue lacinia, fermentum sed quam. Fusce vel sollicitudin leo, eget molestie arcu. Praesent molestie venenatis interdum. Nunc enim turpis, venenatis non consequat sit amet, faucibus vitae erat. Suspendisse consequat dignissim arcu ut tempor. Aenean ut nibh a est pretium sollicitudin nec a mi. Nulla laoreet non lectus vel vestibulum. Suspendisse tristique ex sit amet tortor cursus mattis. Maecenas a dui et lacus sollicitudin suscipit. Nam varius felis sit amet dolor efficitur, non eleifend tellus aliquet. Nunc elementum odio libero, vel mattis eros tempor vel. Aliquam scelerisque sem eget metus semper pharetra. Praesent eget dignissim ante, in tempus eros. Cras euismod volutpat massa.

Etiam volutpat condimentum magna. Curabitur molestie felis eget tincidunt vulputate. Sed ut mattis dui. Fusce nec massa ut dolor tempor imperdiet ac a erat. Donec imperdiet, ex nec molestie pulvinar, lorem tortor faucibus turpis, a interdum elit leo ac ipsum. Maecenas blandit ipsum quam, eu facilisis dui vulputate ut. Cras ultricies, nunc quis faucibus congue, urna enim dignissim turpis, vel porttitor diam ante non ante. Suspendisse eros leo, tempus vitae pellentesque pulvinar, congue sed ante. Duis sit amet nunc vitae dolor volutpat convallis. Nulla quis tortor vitae massa gravida tempor. Donec eget consectetur risus. Duis rhoncus leo nec congue hendrerit. Suspendisse id felis at nisl fringilla sodales. Nunc pulvinar id dolor et efficitur. Curabitur sit amet risus eleifend, scelerisque ante a, malesuada dolor. Nullam sagittis, risus sed dapibus fermentum, urna erat egestas neque, nec dapibus augue risus sed tellus.

Sed luctus ornare nulla at elementum. Praesent aliquet, ex ut tincidunt pulvinar, ipsum mi mollis augue, eget blandit metus tortor vitae sapien. Donec at commodo orci. Ut at nulla id nibh ultricies luctus at vel nulla. Suspendisse congue est et mi placerat, non tempus nibh dapibus. Nullam porta vehicula neque, et hendrerit justo consectetur sed. Sed urna purus, elementum id elit in, vehicula tristique nisi.

Aenean sed magna porttitor eros laoreet mollis non a lacus. Suspendisse interdum vulputate lectus rutrum placerat. Mauris sed fringilla sapien, nec rhoncus massa. Sed mattis pellentesque diam. Ut fermentum maximus ipsum a fermentum. Quisque sed tempor ipsum. Aenean a auctor purus, at consequat sapien. Sed odio sem, iaculis id eros eget, eleifend mattis nunc. Fusce eu malesuada nulla. Sed at iaculis est. Vivamus ultrices ultricies erat sed suscipit. Sed euismod ex at libero consectetur vehicula. Cras quis mauris egestas, porttitor dui non, porttitor odio. Curabitur facilisis elit vel est placerat consectetur. Phasellus sodales massa velit, eget eleifend lorem faucibus in.

Fusce ut pulvinar leo, sed porttitor velit. Nulla luctus fermentum lorem vel luctus. Sed ultrices faucibus augue, sed porttitor neque congue ac. Vivamus sit amet diam sed risus malesuada pretium. Nulla facilisi. Pellentesque mi velit, convallis vitae lorem ac, posuere finibus mi. Phasellus diam turpis, molestie sed tempor id, consequat quis arcu. Mauris suscipit, nisl vel condimentum placerat, urna nunc feugiat eros, vel dignissim dolor mi ac felis. Cras odio elit, mattis in sapien at, tincidunt ornare arcu. Curabitur semper pretium aliquam. Integer malesuada elit sit amet lacus vestibulum porta. Ut dapibus massa maximus eros consequat rutrum. Quisque viverra mollis sem, vel laoreet nisi molestie accumsan.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec tempus mi risus, non scelerisque ipsum fringilla a. Fusce non lacus molestie, scelerisque quam vel, lobortis orci. Suspendisse potenti. Suspendisse turpis neque, convallis ut justo sit amet, ornare aliquet est. Maecenas ut dolor eu arcu elementum placerat in sit amet erat. Integer eget sodales ex. Pellentesque quis nibh euismod nisl mollis sodales. Maecenas posuere feugiat est sit amet egestas. Sed sollicitudin dolor sed accumsan consectetur. In tincidunt quis lorem dictum pellentesque. Fusce turpis lectus, lacinia non viverra ut, porta posuere tellus. Curabitur elementum mollis nisi, ac consequat lectus suscipit ut. Phasellus libero augue, elementum ut volutpat et, porta id nisl. Fusce sit amet neque felis.

Quisque elementum dignissim mi ut vulputate. Suspendisse eu est nec ante pharetra luctus. Morbi facilisis ipsum sed nulla lacinia laoreet. Nullam lacus ligula, dictum eu placerat eget, fermentum ut mi. In fermentum tincidunt cursus. Proin viverra enim consequat lacus tincidunt lacinia. Nam congue, tellus vitae pretium facilisis, libero mi elementum ex, eu finibus lectus justo et lacus. Nunc convallis sapien ac bibendum dapibus. Duis et lectus nisl.

Integer a justo tellus. In nec lectus ac dui luctus ullamcorper sed sed ligula. Cras vitae tempus dolor. Duis a tincidunt nulla. Nunc eget libero et nulla egestas gravida. Nulla tincidunt pretium neque, nec viverra turpis. Duis ac justo tempus, pharetra sem eu, molestie augue. Aliquam erat volutpat. Quisque finibus risus vel malesuada dignissim. Sed tincidunt orci in metus aliquam, ut malesuada urna pellentesque. Quisque odio sapien, vestibulum non lacinia id, sodales eget quam. Vivamus non tortor fermentum, finibus erat non, efficitur enim. Curabitur sit amet velit et arcu vulputate commodo ut quis purus. Fusce non velit eu nibh iaculis tristique id ut mi. Etiam et tortor dignissim, ultricies mauris quis, accumsan neque. Maecenas quis magna dui.`;
}
